# Spring Boot configuration
spring:
  profiles:
    active: development
  # Security configuration
#  security:
#    user:
#      name: user
#      password: user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ang_crud_db
    username: root
    password: 104498Azam
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  # Database
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ang_crud_db
#    username: root
#    password: 104498Azam
#  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
##    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
#    generate-ddl: true
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port